FROM amazonlinux:latest

COPY build/native/nativeCompile/demo /opt/native-app/demo

ARG BUILD_VERSION

ENV DD_PROFILING_ENABLED=true
ENV DD_DATA_STREAMS_ENABLED=true
ENV DD_INTEGRATION_JDBC-DATASOURCE_ENABLED=true
ENV DD_LOGS_INJECTION=true
ENV DD_VERSION=1.0
ENV DD_DBM_PROPAGATION_MODE=full
ENV DD_SERVICE=SP-SC-CFC
ENV DD_LOG_LEVEL=WARN
ENV DD_PROFILING_DIRECTALLOCATION_ENABLED=true

RUN chmod +x /opt/native-app/demo
CMD ./opt/native-app/demo


